version: '3.8'

services:
  redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-volume:/data

  redis_insight:
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - '8001:8001'
    volumes:
      - redis_insight_volume:/db

volumes:
  redis-volume:
  redis_insight_volume: